# Generated by Django 2.1.1 on 2018-09-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('pricebandupper', models.FloatField(default=0)),
                ('totalbuyquantity', models.FloatField(default=0)),
                ('totaltradevalue', models.FloatField(default=0)),
                ('averageprice', models.FloatField(default=0)),
                ('previousclose', models.FloatField(default=0)),
                ('buyprice1', models.FloatField(default=0)),
                ('buyprice2', models.FloatField(default=0)),
                ('buyprice3', models.FloatField(default=0)),
                ('buyprice4', models.FloatField(default=0)),
                ('buyprice5', models.FloatField(default=0)),
                ('sellprice1', models.FloatField(default=0)),
                ('sellprice2', models.FloatField(default=0)),
                ('sellprice3', models.FloatField(default=0)),
                ('sellprice4', models.FloatField(default=0)),
                ('sellprice5', models.FloatField(default=0)),
                ('totaltradedvolume', models.FloatField(default=0)),
                ('lastprice', models.FloatField(default=0)),
            ],
        ),
    ]
