# Generated by Django 2.1.1 on 2018-09-15 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='stocks',
            name='curtime',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, primary_key='true', serialize=False),
            preserve_default=False,
        ),
    ]
