# Generated by Django 2.1.1 on 2018-09-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20180915_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stocks',
            new_name='Stocks1',
        ),
    ]
